config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'hotels#index'

  resources :contacts

  resources :prefectures 
  
  resources :hotels do
    resources :reviews
    resources :bookings
    get 'search', to: 'hotels#search'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord

    belongs_to :hotel

end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/hotel.rb
class Hotel < ApplicationRecord

    mount_uploader :image, PictureUploader 

    belongs_to :prefecture

    has_many :reviews
    has_many :bookings

end

app/models/prefecture.rb
class Prefecture < ApplicationRecord

    has_many :hotels

end

app/models/review.rb
class Review < ApplicationRecord

    belongs_to :hotel

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

    def new
        @hotel = Hotel.find(params[:hotel_id])
        @booking = @hotel.bookings.build
    end

    def create
        hotel = Hotel.find(params[:hotel_id]) 
        booking = Booking.new(booking_params) 
        if booking.save
            redirect_to hotel_booking_path(hotel,booking)
        end
    end

    def index
        @hotel = Hotel.find(params[:hotel_id])
        @bookings = @hotel.bookings
    end

    def show
        @hotel = Hotel.find(params[:hotel_id])
        @booking = Booking.find(params[:id])
    end

    def edit
        @hotel = Hotel.find(params[:hotel_id])
        @booking = Booking.find(params[:id])
    end

    def update
        hotel = Hotel.find(params[:hotel_id])
        booking = Booking.find(params[:id])
        if booking.update(booking_params)
            redirect_to hotel_booking_path(hotel,booking)
        end
    end

    def destroy
        hotel = Hotel.find(params[:hotel_id])
        booking = Booking.find(params[:id])
        if booking.destroy
            redirect_to hotel_bookings_path(hotel)
        end
    end

    private
    def booking_params
        params.require(:booking).permit(:name, :emailaddress, :hotel_id, :checkin, :checkout, :numberofpeople)
    end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

    def new
        @contact = Contact.new
    end

    def create
        contact = Contact.new(contact_params)

        if contact.save
            redirect_to contacts_path
        end
    end

    
    def index
        @contacts =Contact.all
    end

    def show
        @contact = Contact.find(params[:id])
    end

    def edit
        @contact = Contact.find(params[:id])
    end

    def update
        contact = Contact.find(params[:id])
        contact = contact.update(contact_params)
        redirect_to contacts_path(contact)
    end

    def destroy
        contact = Contact.find(params[:id])
        contact.destroy
        redirect_to contacts_path
    end

    private
    def contact_params
        params.require(:contact).permit(:name, :emailaddress, :body)
    end


end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController



    def new
        @hotel = Hotel.new
    end

    def create
        @hotel = Hotel.new(contact_params)

        if @hotel.save
            redirect_to hotels_path
        end
    end

    

    def index

        #以下、ransack

        
        @q = Hotel.ransack(params[:q])
        @hotels = @q.result.includes(:prefecture).page(params[:page])
        

        @prefectures = Prefecture.all


        #以上、ransack
        
    end

    def show
        @hotel = Hotel.find(params[:id])

        @reviews = @hotel.reviews.all
    end

    def edit
        @hotel = Hotel.find(params[:id])
    end

    def update
        @hotel = Hotel.find(params[:id])
        @hotel = @hotel.update(hotel_params)
        redirect_to hotels_path(@hotel)
    end

    def destroy
        @hotel = Hotel.find(params[:id])
        @hotel.destroy
        redirect_to hotels_path
    end


    private
    
    def hotel_params
        params.require(:hotel).permit(:name, :body, :image, :prefecture_id)
    end


    #以下、ransack

    def search_params
        params.require(:q).permit(:name_cont, :prefecture_id_eq)
    end

    #以上、ransack




end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController


    def new
        @prefecture = Prefecture.new
    end

    def create
        @prefecture = Prefecture.new(contact_params)

        if @prefecture.save
            redirect_to prefectures_path
        end
    end



    def index

        
        @prefectures = Prefecture.all


    end

    def show
        @prefecture = Prefecture.find(params[:id])
        @hotels = @prefecture.hotels
    end

    def edit
        @prefecture = Prefecture.find(params[:id])
    end

    def update
        prefecture = Prefecture.find(params[:id])
        prefecture = prefecture.update(prefecture_params)
        redirect_to prefectures_path(prefecture)
    end

    def destroy
        prefecture = Prefecture.find(params[:id])
        prefecture.destroy
        redirect_to prefectures_path
    end



    private
    def prefecture_params
        params.require(:prefecture).permit(:name)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def new
        @hotel = Hotel.find(params[:hotel_id])
        @review = @hotel.reviews.build
    end

    def create
        @hotel = Hotel.find(params[:hotel_id])
        @review = Review.new(review_params)
        if @review.save
            redirect_to hotel_reviews_path(@hotel)
        end
    end

    def index
        @hotel = Hotel.find(params[:hotel_id])
        @reviews = @hotel.reviews
    end

    def show
        @hotel = Hotel.find(params[:hotel_id])
        @review = Review.find(params[:id])
    end

    def edit
        @hotel = Hotel.find(params[:hotel_id])
        @review = Review.find(params[:id])
    end

    def update
        @hotel = Hotel.find(params[:hotel_id])
        @review = Review.find(params[:id])
        if @review.update(review_params)
            redirect_to hotel_reviews_path(@hotel)
        end
    end

    def destroy
        @hotel = Hotel.find(params[:hotel_id])
        @review = Review.find(params[:id])
        if @review.destroy
            redirect_to hotel_reviews_path(@hotel)
        end
    end

    private
    def review_params
        params.require(:review).permit(:name, :body, :hotel_id, :title, :rate)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookings/_form.html.erb
<%= form_with(model: [@hotel, booking], local: true) do |form| %>

    <% if booking.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

            <ul>
                <% booking.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div>
        <%= form.label :代表者指名 %>
        <%= form.text_field :name %>
    </div>

    <div>
        <%= form.label :代表者連絡先 %>
        <%= form.text_field :emailaddress %>
    </div>

    <div>
        <%= form.label :チェックイン日 %>
        <%= form.date_select :checkin %>
    </div>

    <div>
        <%= form.label :チェックアウト日 %>
        <%= form.date_select :checkout %>
    </div>

    <div>
        <%= form.label :人数 %>
        <%= form.select :numberofpeople, [0,1,2,3,4,5] %>
    </div>

    <%= form.hidden_field :hotel_id %>

  

    <div class="actions">
        <%= form.submit %>
    </div>
    
<% end %>

app/views/bookings/edit.html.erb
<div class="container">
    <h1>予約の訂正</h1>
    <hr>
    <%= render 'form' , booking: @booking %>
</div>

app/views/bookings/new.html.erb
<div class="container">
    <h1><%= @hotel.name %>の予約</h1>
    <hr>
    <%= render 'form', booking: @booking %>
</div>

app/views/bookings/show.html.erb
<div class="container">
    <h1>予約が完了しました。</h1>
    <p>予約の詳細は以下の通りです。</p>
    <hr>
    <div>
        <p>ホテル名: <%= @booking.hotel.name %> </p>
        <p>氏名: <%= @booking.name %> </p>
        <p>お客様連絡先: <%= @booking.emailaddress %> </p>
        <p>チェックイン予定日: <%= @booking.checkin %> </p>
        <p>チェックアウト予定日: <%= @booking.checkout %> </p>
        <p>宿泊人数: <%= @booking.numberofpeople %> </p>
    </div>

    <%= link_to '訂正はこちらから', edit_hotel_booking_path %>
    <%= link_to 'ホテルの詳細はこちら', hotel_path(@booking.hotel) %>
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
    <!-- name -->
        <div class="field">
            <p class="contact-label"><%= form.label :Name %>
            <%= form.text_field :name, id: :contacter_name %>
        </div>
    <!-- Email Address -->
        <div class="field">
            <%= form.label :Email_Address %>
            <%= form.text_field :emailaddress, id: :contacter_email %>
        </div>
    <br>
    <!-- Body -->
        <div class="field">
            <%= form.label :お問い合わせ内容 %>
            <%= form.text_area :body, id: :contact_body %>
        </div>
    <!-- submit -->
    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>問い合わせ内容の修正フォーム</h1>
<br>
<%= render 'form', contact: @contact %>
    
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>問い合わせ一覧</h1>
<table>
    <tr>
        <th>名前</th>
        <th>問い合わせ内容</th>
        <th>連絡先</th>
    </tr>
    <% @contacts.each do |contact| %>
        <tr>
            <td><%= link_to contact.name, contact_path(contact) %></td>
            <td class="body"><%= contact.body %></td>
            <td><%= contact.emailaddress %></td>
        </tr>
    <% end %>
</table>

<p><%= link_to'新規問い合わせはこちらから', new_contact_path %></p>

app/views/contacts/new.html.erb
<h1>問い合わせフォーム</h1>
<hr>
<%= render 'form', contact: @contact %>
    
<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<h1>問い合わせ詳細</h1>
<hr>
<p>名前:<%= @contact.name %></p>
<p>問い合わせ内容<br><%= @contact.body %></p>
<p>連絡先:<%= @contact.emailaddress %></p>
<hr>
<p>
    <%= link_to '修正', edit_contact_path(@contact) %>
    <%= link_to '削除', contact_path(@contact), data: { confirm: '問い合わせを取りやめてよろしいですか？' },  method: :delete  %>
</p>
<br>
<%= link_to'Back',contacts_path %>

app/views/hotels/_hotel_search_form.html.erb
<%= search_form_for(@q, url:hotels_path) do |form| %>

    <div class="row">

        <div class="col-md-6">
            <%= form.label :ホテル名%>
            <%= form.search_field :name_cont %>
            <%= form.submit %> 
        </div>

        <div class="col-md-6">
            <%= form.label :都道府県名 %>
            <%= form.collection_select :prefecture_id_eq, @prefectures, :id, :name, :include_blank => '-' %>
            <%= form.submit %> 
        </div>


    </div>

<% end %>

app/views/hotels/_prefecture_search_form.html.erb
<%= search_form_for(@q2, url:hotels_path, as: :q2) do |form| %>

    <div>

        <%= form.label :都道府県名 %>
        <%= form.collection_select :prefecture_id_eq, @prefectures, :id, :name, :include_blank => '-' %>
        <%= form.submit %> 

    </div>
    
<% end %>

app/views/hotels/index.html.erb
<div class="container">
    <h1>ホテルの一覧</h1>
    <hr>

   
    
    <%= render 'hotel_search_form' %>

        

    


    <hr>

    <div class="row">
        <% @hotels.each do |hotel| %>
                <div class="col-md-3 mb-20"> 
                    <div class="card h-100">    
                        <div class="card-img-top h-40">
                            <%= link_to image_tag(hotel.image_url, class: "top-image"), hotel_path(hotel) if hotel.image.present?%>
                        </div>
                        <div class="card-body h-52">
                            <h5 class="card-title"><%= link_to hotel.name, hotel_path(hotel) %></h5>
                            <small class="card-prefecture"><%= link_to hotel.prefecture.name, prefecture_path(hotel.prefecture)%></small><hr>
                            <p class="card-text"><span class=><%= hotel.body.truncate(40) %></span></p>
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">
                                <%= link_to'レビューを見る', hotel_reviews_path(hotel) %>
                            </small>
                        </div>
                    </div>
                </div>
        <% end %>
    </div>
</div>

app/views/hotels/show.html.erb
<div class="container">

    <h1><%= @hotel.name %></h1>

    <%# pathの記述、是枝さんに教えていただきました。 %>
    <%= link_to @hotel.prefecture.name, prefecture_path(@hotel.prefecture) %>

    <hr>
    <div class="row">
        <p class="col-md-3"><%= image_tag(@hotel.image_url, class: "show-image") if @hotel.image.present? %></p>
        <p class="col-md-9"><%= @hotel.body %></p>
    </div>
    <br>
    <%= link_to'ご予約はこちらから', new_hotel_booking_path(@hotel) %><br>
    <%= link_to'評価一覧', hotel_reviews_path(@hotel) %><br>
    <hr>
    <div class="row">
        <% @reviews.each do |review| %>
            <div class="col-md-10">
                <b><%= link_to review.title, hotel_review_path(@hotel, review) %></b><br>
                <%= review.name %><br>
                <p class="body">
                    <%= review.rate %><br>
                    <%= review.body.truncate(45) %>
                </p><hr>
            </div>
        <% end %>
    </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <div class="container">
        <nav class="navbar navbar-expand-sm navbar-light">
          <%= image_tag '亀.jpg', width: 40, height: 40, class: 'mx-2', alt: 'ホテルのアイコン' %>
          <a class="navbar-brand font-italic" href="/" style="font-size: 30px"><u>Hotel Project</u></a>
          <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div id="menu" class="collapse navbar-collapse d-flex justify-content-end">
            <ul class="navbar-nav">
              <li class="nav-item"><a href="/" class="nav-link">トップページ</a></li>
              <li class="nav-item"><a href="/contacts/new" class="nav-link">お問い合わせ</a></li>
            </ul>
          </div>
        </nav>  
      </div>
    </header>
    
    <%= yield %>

    <footer class="mt-5">
      <p class="text-center text-muted display-5 bg-light">Hotel Project</p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/prefectures/show.html.erb
<div class="container">
    <h1><%= @prefecture.name %></h1>
    <hr>
    <div>
        <p>ホテルの一覧</p>
        <ul>
            <% @hotels.each do |hotel| %>   
                <li><%= link_to hotel.name, hotel_path(hotel) %></li>
            <% end %>
        </ul>    
    </div>

    <%= link_to'トップ', root_path %>
</div>

app/views/reviews/_form.html.erb
<%= form_with(model: [@hotel, review], local: true) do |form| %>

    <% if review.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

            <ul>
                <% review.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form">
        <%= form.label :レビュー者名 %>
        <%= form.text_field :name %>
    </div>

    <div class="form">
        <%= form.label :レビュータイトル %>
        <%= form.text_field :title %>
    </div>

    <div class="form">
        <%= form.label :満足度 %>
        <%= form.select :rate,[0,0.5,1,1.5,2,2.5,3,3.5,4,4.5,5] %>
    </div>

    <div class="form">
        <%= form.label :本文 %>
        <%= form.text_area :body %>
    </div>

    <%= form.hidden_field :hotel_id %>

  

    <div class="actions">
        <%= form.submit %>
    </div>
    
<% end %>

app/views/reviews/index.html.erb
<div class="container">

    <h1><%= link_to @hotel.name, hotel_path(@hotel) %>の評価一覧</h1>
    <hr>
    <div>
        <% @reviews.each do |review| %>
            <b><%= link_to review.title, hotel_review_path(@hotel, review) %></b><br>
            <%= review.name %><br>
            <p class="body">
                <%= review.rate %><br>
                <%= review.body.truncate(110) %>
            </p><hr>
        <% end %>
    </div>
    <%= link_to 'レビューする', new_hotel_review_path(@hotel) %>

</div>

app/views/reviews/new.html.erb
<div class="container">
    <h1>新規レビューの作成</h1>
    <hr>
    <%= render 'form', review: @review %>
    <%= link_to 'Back', hotel_reviews_path(@hotel) %>
</div>

app/views/reviews/show.html.erb
<div class="container">

    <h1><%= @review.name %>さんによる評価の詳細</h1>
    <hr>
    <div>
        <b><%= @review.title %></b><br>
        <p class="body">
            <%= @review.rate %><br>
            <%= @review.body %>
        </p>
    </div>
    <%= link_to'レビュー一覧に戻る', hotel_reviews_path(@hotel) %>

</div>